version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo In pre_build phase...
      - mvn test
  build:
    commands:
      - echo In build phase...
      - mvn package -DskipTests=true
  post_build:
    commands:
      - echo In post_build phase...
artifacts:
  files:
    - target/*.jar
  discard-paths: yes